import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import twitter from "../public/twitter.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* LEFT  */}
        <section className={styles.imgContainer}>
          <div className={styles.twitterContainer}>
            <Image
              className={styles.twitter}
              src={twitter}
              alt="twitter image"
              layout="fill"
            />
          </div>
          <Image
            src="https://abs.twimg.com/sticky/illustrations/lohp_1302x955.png"
            alt="twitter image"
            className={styles.imgLogin}
            layout="fill"
          />
        </section>
        {/* RIGHT */}
        <aside className={styles.rightContainer}>
          <div className={styles.icone}>
            <Image src={twitter} alt="twitter" width="100%" height="100%" />
          </div>
          <h1>
            Ça se passe
            <br /> maintenant{" "}
          </h1>
          <h2>{`Rejoignez Twitter dès 'hui`}</h2>
          <div className={styles.btnsContainer}>
            <button>{`S'inscrire avec Google`}</button>
            <button>{`S'inscrire avec Apple`}</button>
            <p>ou</p>
            <button>{`S'inscrire avec un numéro de téléphone`}</button>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo,
              excepturi totam. Impedit neque illum ab assumenda enim saepe
              consequuntur nulla.
            </p>
          </div>
          <h2>Vous avez déjà un compte ?</h2>
          <button>Se connecter</button>
        </aside>
      </main>
    </div>
  );
}
